branches:
  only:
    - master

version: 2.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '**/*.md'

nuget:
  account_feed: true
  
before_build:
- cmd: nuget restore src
- ps: $file = "$env:appveyor_build_folder\src\AnyStatus.Plugins\AnyStatus.Plugins.nuspec"
- ps: $xml = [xml](Get-Content $file)
- ps: $xml.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
- ps: $xml.Save($file)

build:
  publish_nuget: true
  verbosity: minimal
  
deploy:
  provider: Environment
  name: AnyStatus
